In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('C:\\Users\\vedas\\OneDrive\\Attachments\\Desktop\\College Work\\free\\TrainingDVpython\\Ecommerce_analysis\\data.csv', encoding="latin1")
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [4]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

In [6]:
print("Shape (rows, cols:)",df.shape)

Shape (rows, cols:) (541909, 8)

In [7]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [ ]:
#check missing values using isnull()
print("\nColumn-wise missing values \n",df.isnull().sum())

Column-wise missing values
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
df.duplicated().sum()

5268

In [ ]:
#gives the statistical summary of the data
df.describe()

In [11]:
#drop the rows and columns with missing values
df.dropna(subset = ["Description"], inplace = True)

In [ ]:
#is there data is missing customer id, we suppose is Guest transaction
df_with_customer = df.dropna(subset= ["CustomerID"]).copy()
df_with_customer["CustomerID"] = df_with_customer["CustomerID"].astype("int")

In [17]:
#check Iscancelled Payment and Invoice number and check Data type "confirm false",'cancelled true'
df['isCancelled'] = df['InvoiceNo'].astype(str).str.startswith("C")
df['isCancelled']

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: isCancelled, Length: 540455, dtype: bool

In [18]:
~df['isCancelled']

0         True
1         True
2         True
3         True
4         True
          ...
541904    True
541905    True
541906    True
541907    True
541908    True
Name: isCancelled, Length: 540455, dtype: bool

In [22]:
#Create a new DataFrame only keeping  Valid Transaction
#Keep only those rows where the order is not cancelled, the quantity is greater than 0, and the unit price is greater than 0
df_clean = df[
   
    (~df['isCancelled']) &           #Keep only rows there iscancelled is false
    (df['Quantity']>0)  &            #keep only those rows whose quantity is greater than 0  Because a negative quantity usually represents a returned or cancelled item.
    (df['UnitPrice']>0)              #Keep only and check rows Unitprice is greater than 0
    ].copy()                         #create a separate copy of the Filtered DataFrame       

#Without .copy(), changes made to df_clean may also affect the original DataFrame or produce a SettingWithCopyWarning.

#With .copy(), df_clean is a separate DataFrame that you can safely modify.

In [23]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,isCancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,False
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,False
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,False
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,False
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,False
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,False

In [ ]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean["InvoiceDate"]) #"Convert this text into actual date and time values After conversion, Pandas understands that these are dates.
# Now the column's data type changes from:
# object (string)
# to
# datetime64[ns]
#Once the column is in datetime format, you can perform date-related operations.
#The converted datetime values replace the original string values in the DataFrame.
df_clean["InvoiceDate"]
# InvoiceDate Column
#         │
#         ▼
# Stored as Text (String)
#         │
#         ▼
# pd.to_datetime()
#         │
#         ▼
# Converted into Date & Time Format
#         │
#         ▼
# Stored back into InvoiceDate column
#         │
#         ▼
# Display the InvoiceDate column

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530104, dtype: datetime64[ns]

In [ ]:
df_clean["TotalPrice"] = np.multiply(df_clean["Quantity"],df_clean["UnitPrice"])
#The purpose of this code is to calculate the total price of each product purchased.
#It tells us how many items were purchased.
#It tells us the price of one item.
#np.multiply() is a NumPy function that multiplies two values.
#It works like the * operator but can multiply entire columns element by element.

df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,isCancelled,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,False,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,False,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False,20.34
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,False,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,False,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,False,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,False,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,False,14.85

In [27]:
df_clean['TotalPrice']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 530104, dtype: float64

In [ ]:
print("STEP3: Data Cleaned")
print("Original rows:",df.shape[0],"|Clean rows:",df_clean.shape[0])
print("Cancelled order removed:",df["isCancelled"].sum())
print(df_clean[["InvoiceNo","Quantity","UnitPrice","TotalPrice","InvoiceDate"]])
print("\n")

In [29]:
#extract the year from the 'InvoiceDate' column and store it in a new column called 'Year'
df_clean['Year'] = df_clean['InvoiceDate'].dt.year
#extract the month (1-12) from the 'invoiceDate' column
df_clean['Month'] = df_clean['InvoiceDate'].dt.month
#Extract the day of the month (1-31) from the 'InvoiceDate' column
df_clean['Day'] = df_clean['InvoiceDate'].dt.day
#extract the hour (0-23) from the 'InvoiceDate' column and store it in a new column called 'Hour'
df_clean['Hour'] = df_clean['InvoiceDate'].dt.hour

#extract the day of the week (0-6) from the 'InvoiceDate' column and store it in a new column called 'DayOfWeek'
df_clean['DayOfWeek'] = df_clean['InvoiceDate'].dt.dayofweek

In [ ]:
print("STEP4: Date features added")
print(df_clean[["InvoiceDate","Year","Month","DayOfWeek","Hour"]].head(10))
print("\n" )