In [2]:
# What is Pandas?
# Pandas is an open-source Python library used for data manipulation, data analysis, and data cleaning. It is one of the most important libraries in Data Science, Machine Learning, and Data Analytics.

# Series → One-dimensional data (like a single column).
# DataFrame → Two-dimensional tabular data (rows and columns), similar to an Excel spreadsheet or SQL table.


# Why is Pandas used in Data Science?

# Almost every data science project follows this workflow:

# Collect Data
#       ↓
# Load Data (Pandas)
#       ↓
# Clean Data
#       ↓
# Analyze Data
#       ↓
# Visualize Data
#       ↓
# Build ML Model

# 1. Read Data

# Load data from different file formats.'Example'

# df = pd.read_csv("data.csv")
# df = pd.read_excel("data.xlsx")
# df = pd.read_json("data.json")


# 2. Inspect Data 'Example'

# Understand the dataset.

# df.head()
# df.tail()
# df.info()
# df.describe()5. Filtering Data

# Select rows based on conditions. 'Example'

# df[df["Age"] > 30]

# df[df["Salary"] > 50000]
# df.shape
# df.columns
# df.dtypes

# 3. Data Cleaning 

# Handle missing and incorrect values.'Example'

# df.dropna()
# df.fillna(0)
# df.drop_duplicates()
# df.replace()


# 4. Data Selection ('Example')

# Select rows and columns.

# df["Age"]

# df[["Name", "Age"]]

# df.loc[0]

# df.iloc[5]

# 6. Create New Columns 'Example'
# df["Total"] = df["Quantity"] * df["Price"]


# 5. Filtering Data
# 'Example'
# Select rows based on conditions.

# df[df["Age"] > 30]

# df[df["Salary"] > 50000]


# 7. Sorting Data  'Example'
# df.sort_values("Salary")

# df.sort_values("Salary", ascending=False)

# 8. Grouping Data 'Example'

# Summarize data by categories.

# df.groupby("Department")["Salary"].mean()


# 9. Aggregation  'Example'

# Calculate summary statistics.

# df.agg({
#     "Salary": "mean",
#     "Age": "max"
# })


# 10. Statistical Analysis  'Example'
# df.mean()

# df.median()

# df.std()

# df.min()

# df.max()

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('C:\\Users\\vedas\\OneDrive\\Attachments\\Desktop\\College Work\\free\\TrainingDVpython\\Ecommerce_analysis\\data.csv', encoding="latin1")
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [5]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

In [7]:
print("Shape (rows, cols:)",df.shape)

Shape (rows, cols:) (541909, 8)

In [8]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [9]:
#check missing values using isnull()
print("\nColumn-wise missing values \n",df.isnull().sum())

Column-wise missing values
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
df.duplicated().sum()

5268

In [11]:
#gives the statistical summary of the data
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [12]:
#drop the rows and columns with missing values
df.dropna(subset = ["Description"], inplace = True)

In [13]:
#is there data is missing customer id, we suppose is Guest transaction
df_with_customer = df.dropna(subset= ["CustomerID"]).copy()
df_with_customer["CustomerID"] = df_with_customer["CustomerID"].astype("int")

In [15]:
#check Iscancelled Payment and Invoice number and check Data type "confirm false",'cancelled true'
df['isCancelled'] = df['InvoiceNo'].astype(str).str.startswith("C")
df['isCancelled']

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: isCancelled, Length: 540455, dtype: bool

In [16]:
~df['isCancelled']

0         True
1         True
2         True
3         True
4         True
          ...
541904    True
541905    True
541906    True
541907    True
541908    True
Name: isCancelled, Length: 540455, dtype: bool

In [17]:
#Create a new DataFrame only keeping  Valid Transaction
#Keep only those rows where the order is not cancelled, the quantity is greater than 0, and the unit price is greater than 0
df_clean = df[
   
    (~df['isCancelled']) &           #Keep only rows there iscancelled is false
    (df['Quantity']>0)  &            #keep only those rows whose quantity is greater than 0  Because a negative quantity usually represents a returned or cancelled item.
    (df['UnitPrice']>0)              #Keep only and check rows Unitprice is greater than 0
    ].copy()                         #create a separate copy of the Filtered DataFrame       

#Without .copy(), changes made to df_clean may also affect the original DataFrame or produce a SettingWithCopyWarning.

#With .copy(), df_clean is a separate DataFrame that you can safely modify.

In [18]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,isCancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,False
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,False
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,False
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,False
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,False
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,False
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,False

In [19]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean["InvoiceDate"]) #"Convert this text into actual date and time values After conversion, Pandas understands that these are dates.
# Now the column's data type changes from:
# object (string)
# to
# datetime64[ns]
#Once the column is in datetime format, you can perform date-related operations.
#The converted datetime values replace the original string values in the DataFrame.
df_clean["InvoiceDate"]
# InvoiceDate Column
#         │
#         ▼
# Stored as Text (String)
#         │
#         ▼
# pd.to_datetime()
#         │
#         ▼
# Converted into Date & Time Format
#         │
#         ▼
# Stored back into InvoiceDate column
#         │
#         ▼
# Display the InvoiceDate column

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530104, dtype: datetime64[ns]

In [20]:
df_clean["TotalPrice"] = np.multiply(df_clean["Quantity"],df_clean["UnitPrice"])
#The purpose of this code is to calculate the total price of each product purchased.
#It tells us how many items were purchased.
#It tells us the price of one item.
#np.multiply() is a NumPy function that multiplies two values.
#It works like the * operator but can multiply entire columns element by element.

df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,isCancelled,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,False,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,False,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,20.34
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,False,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,False,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,False,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,False,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,False,14.85

In [21]:
df_clean['TotalPrice']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 530104, dtype: float64

In [22]:
print("STEP3: Data Cleaned")
print("Original rows:",df.shape[0],"|Clean rows:",df_clean.shape[0])
print("Cancelled order removed:",df["isCancelled"].sum())
print(df_clean[["InvoiceNo","Quantity","UnitPrice","TotalPrice","InvoiceDate"]])
print("\n")

STEP3: Data Cleaned
Original rows: 540455 |Clean rows: 530104
Cancelled order removed: 9288
       InvoiceNo  Quantity  UnitPrice  TotalPrice         InvoiceDate
0         536365         6       2.55       15.30 2010-12-01 08:26:00
1         536365         6       3.39       20.34 2010-12-01 08:26:00
2         536365         8       2.75       22.00 2010-12-01 08:26:00
3         536365         6       3.39       20.34 2010-12-01 08:26:00
4         536365         6       3.39       20.34 2010-12-01 08:26:00
...          ...       ...        ...         ...                 ...
541904    581587        12       0.85       10.20 2011-12-09 12:50:00
541905    581587         6       2.10       12.60 2011-12-09 12:50:00
541906    581587         4       4.15       16.60 2011-12-09 12:50:00
541907    581587         4       4.15       16.60 2011-12-09 12:50:00
541908    581587         3       4.95       14.85 2011-12-09 12:50:00

[530104 rows x 5 columns]

In [23]:
#extract the year from the 'InvoiceDate' column and store it in a new column called 'Year'
df_clean['Year'] = df_clean['InvoiceDate'].dt.year
#extract the month (1-12) from the 'invoiceDate' column
df_clean['Month'] = df_clean['InvoiceDate'].dt.month
#Extract the day of the month (1-31) from the 'InvoiceDate' column
df_clean['Day'] = df_clean['InvoiceDate'].dt.day
#extract the hour (0-23) from the 'InvoiceDate' column and store it in a new column called 'Hour'
df_clean['Hour'] = df_clean['InvoiceDate'].dt.hour

#extract the day of the week (0-6) from the 'InvoiceDate' column and store it in a new column called 'DayOfWeek'
df_clean['DayOfWeek'] = df_clean['InvoiceDate'].dt.dayofweek

In [24]:
print("STEP4: Date features added")
print(df_clean[["InvoiceDate","Year","Month","DayOfWeek","Hour"]].head(10))
print("\n" )

STEP4: Date features added
          InvoiceDate  Year  Month  DayOfWeek  Hour
0 2010-12-01 08:26:00  2010     12          2     8
1 2010-12-01 08:26:00  2010     12          2     8
2 2010-12-01 08:26:00  2010     12          2     8
3 2010-12-01 08:26:00  2010     12          2     8
4 2010-12-01 08:26:00  2010     12          2     8
5 2010-12-01 08:26:00  2010     12          2     8
6 2010-12-01 08:26:00  2010     12          2     8
7 2010-12-01 08:28:00  2010     12          2     8
8 2010-12-01 08:28:00  2010     12          2     8
9 2010-12-01 08:34:00  2010     12          2     8

In [ ]:
#step5"Key Business Metrics
#Calulate the total revenue generated from all valid transactions.
#Formula:Total Revenue = Sum of all TotalPrice values

total_revenue = np.sum(df_clean['TotalPrice'])

#Calculate the total number of unique orders(invoices)
#nunique() counts unique InvoiceNo values
#If an invoice contains multiple products, it is still counted as ONE order
total_orders = df_clean['InvoiceNo'].nunique()

#Calculate the total numbers of unique customers.
#nunique()  counts distinct CustomerID values 
#If a customer places multiple orders,they are counted only once.
total_customers = df_clean["CustomerID"].nunique()

#Calculate the Average Order Value(AOV)
#Step1:Group all rows by InvoiceNo (each invoice may contain multiple products)
#step2:Sum the TotaLPrice of all products within each invoice.
#step3: Calculate the average of all invoice totals
#(Calculates the average amount spent per order by first finding the total value of each invoice and then averaging those totals.)
avg_order_value = df_clean.groupby("InvoiceNo")["TotalPrice"].sum().mean()


print(total_revenue)
print(total_orders)
print(total_customers)
print(avg_order_value)


# Original Data

# InvoiceNo    TotalPrice
# 1001            20
# 1001            30
# 1002            40
# 1002            10
# 1003            50
#         │
#         ▼
# groupby("InvoiceNo")
#         │
#         ▼
# 1001 → 20, 30
# 1002 → 40, 10
# 1003 → 50
#         │
#         ▼
# sum()
#         │
#         ▼
# 1001 → 50
# 1002 → 50
# 1003 → 50
#         │
#         ▼
# mean()
#         │
#         ▼
# Average Order Value = 50

10666684.544
19960
4338
534.403033266533

In [ ]:
#Groups the data by product name, calculates the total revenue earned from each product, 
# sorts the products from highest to lowest revenue, and returns the top 10 products.
top_products_revenue = df_clean.groupby("Description")["TotalPrice"].sum().sort_values(ascending=False).head(10)
#Groups the data by product name, calculates the total quantity sold for each product, s
# orts the products from highest to lowest quantity sold, and returns the top 10 products.
top_products_quantity = df_clean.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(10)
print("Step6:Top 10 Prodcuts by Revenue")
print(top_products_revenue)
print("Step6:Top 10 Prodcuts by Quantity")
print(top_products_quantity)

Step6:Top 10 Prodcuts by Revenue
Description
DOTCOM POSTAGE                        206248.77
REGENCY CAKESTAND 3 TIER              174484.74
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106292.77
PARTY BUNTING                          99504.33
JUMBO BAG RED RETROSPOT                94340.05
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
Manual                                 78112.82
POSTAGE                                78101.88
RABBIT NIGHT LIGHT                     66964.99
Name: TotalPrice, dtype: float64
Step6:Top 10 Prodcuts by Quantity
Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     55047
JUMBO BAG RED RETROSPOT               48474
WHITE HANGING HEART T-LIGHT HOLDER    37891
POPCORN HOLDER                        36761
ASSORTED COLOUR BIRD ORNAMENT         36461
PACK OF 72 RETROSPOT CAKE CASES       36419
RABBIT NIGHT LIGHT                    30788
MINI PAINT SET VINTAGE                26633
Name: Quantity, dtype: int64

In [ ]:
#STEP 7:Country-wise Analysis
country_revenue = (
    df_clean.groupby("Country")["TotalPrice"]
    .sum()
    .astype(int)
    .sort_values(ascending=False)
)
print("Step7:Revenue by Country")
print(country_revenue.head(10))

# Original DataFrame
#         │
#         ▼
# Group rows by Country
#         │
#         ▼
# Select TotalPrice column
#         │
#         ▼
# Add all sales of each country
#         │
#         ▼
# Convert revenue to integers
#         │
#         ▼
# Sort from highest revenue to lowest
#         │
#         ▼
# Store in country_revenue

Step7:Revenue by Country
Country
United Kingdom    9025222
Netherlands        285446
EIRE               283453
Germany            228867
France             209715
Australia          138521
Spain               61577
Switzerland         57089
Belgium             41196
Sweden              38378
Name: TotalPrice, dtype: int32

In [ ]:
#STEP8: MONTHLY SALES TREND
#create  a new column containing only the year and month from the invoicedate
df_clean["YearMonth"] = df_clean["InvoiceDate"].dt.to_period("M")

#Calculate the total sales(revenue) for each Year-month 
monthly_sales = df_clean.groupby("YearMonth")["TotalPrice"].sum()
print("Step8:Monthly Sales Trend")
print(monthly_sales)